id: https://waldronlab.io
name: cMD_Curation_Schema
description: ''
version: 0.0.1
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
classes:
  dh_interface:
    name: dh_interface
    description: A DataHarmonizer interface
    from_schema: https://example.com/cMD_Curation_Schema
  Sample:
    slots:
    - sample_id
    - age
    - age_unit
    - age_group
    - control
    - target_condition
    - disease
    - treatment
    - sample_id
    - age
    - age_unit
    - age_group
    - control
    - target_condition
    - disease
    - treatment
    is_a: dh_interface
    slot_usage:
      sample_id:
        rank: 1
        slot_group: Database Identifiers
      age:
        rank: 2
        slot_group: Participant
      age_unit:
        rank: 3
        slot_group: Participant
      age_group:
        rank: 4
        slot_group: Participant
      control:
        rank: 5
        slot_group: Participant
      target_condition:
        rank: 6
        slot_group: Participant
      disease:
        rank: 7
        slot_group: Participant
      treatment:
        rank: 8
        slot_group: Participant
slots:
  sample_id:
    name: sample_id
    title: sample_id
    description: The user-defined name for the sample.
    range: WhitespaceMinimizedString
    identifier: true
    required: true
  age:
    name: age
    title: age
    description: Age of the subject using the unit specified under 'age_unit' column
    examples:
    - value: '2'
    slot_uri: NCIT:C25150
    range: integer
    minimum_value: '0'
    maximum_value: '200'
  age_unit:
    name: age_unit
    title: age_unit
    description: Unit of the subject's age specified under 'age' column
    examples:
    - value: Year
    slot_uri: NCIT:C50400
    range: age unit menu
    structured_pattern:
      syntax: '{Title_Case}'
      partial_match: false
      interpolated: true
  age_group:
    name: age_group
    title: age_group
    description: 11 <= Adolescent < 18|18 <= Adult < 65|2 <= Children 2-11 Years Old
      < 11|65 <= Elderly < 130|0 <= Infant < 2
    examples:
    - value: Children 2-11 Years Old
    slot_uri: NCIT:C20587
    range: age group menu
    recommended: true
  control:
    name: control
    title: control
    description: Whether the sample is control, case, or not used in the study
    examples:
    - value: Study Control
    range: control menu
    required: true
  target_condition:
    name: target_condition
    title: target_condition
    description: Main phenotype(s) of interest in a given study
    range: target condition menu
    multivalued: true
    required: true
  disease:
    name: disease
    title: disease
    description: Reported disease type(s) for a participant. 'Healthy' if no disease
      assessed under a given study is detected
    range: disease menu
    multivalued: true
  treatment:
    name: treatment
    title: treatment
    description: Medications or treatments against the diseases
    range: treatment menu
    multivalued: true
enums:
  treatment menu:
    name: treatment menu
    permissible_values:
      Mesalamine:
        text: Mesalamine
        meaning: NCIT:C29249
      Acarbose:
        text: Acarbose
        meaning: NCIT:C983
      Angiotensin-Converting Enzyme Inhibitors:
        text: Angiotensin-Converting Enzyme Inhibitors
        meaning: SCDO:0000055
      Albendazole:
        text: Albendazole
        meaning: NCIT:C47384
      Amiodarone:
        text: Amiodarone
        meaning: NCIT:C62002
      EC 3.4.23.15 (renin) inhibitor:
        text: EC 3.4.23.15 (renin) inhibitor
        meaning: CHEBI:166822
      Antihelminthic Agent:
        text: Antihelminthic Agent
        meaning: NCIT:C250
      Antihypertensive Agents:
        text: Antihypertensive Agents
        meaning: SCDO:0000067
      Anti-Retroviral Agents:
        text: Anti-Retroviral Agents
        meaning: OMIT:0023531
      antiviral drug:
        text: antiviral drug
        meaning: CHEBI:36044
      Anti-diabetic Agent:
        text: Anti-diabetic Agent
        meaning: NCIT:C29711
      Antilipidemic Agent:
        text: Antilipidemic Agent
        meaning: NCIT:C29703
      Antineoplastic Agent:
        text: Antineoplastic Agent
        meaning: NCIT:C274
      Thrombolytic Agent:
        text: Thrombolytic Agent
        meaning: NCIT:C29750
      Aspirin:
        text: Aspirin
        meaning: NCIT:C287
      Angiotensin II Receptor Antagonist:
        text: Angiotensin II Receptor Antagonist
        meaning: NCIT:C66930
      Azathioprine:
        text: Azathioprine
        meaning: NCIT:C290
      Beta-Adrenergic Antagonist:
        text: Beta-Adrenergic Antagonist
        meaning: NCIT:C29576
      Calcium Channel Blocker:
        text: Calcium Channel Blocker
        meaning: NCIT:C333
      Clopidogrel:
        text: Clopidogrel
        meaning: NCIT:C61686
      Corticosteroid:
        text: Corticosteroid
        meaning: NCIT:C2322
      Anti-CTLA-4 Monoclonal Antibody:
        text: Anti-CTLA-4 Monoclonal Antibody
        meaning: NCIT:C128036
      Centrally acting hypotensive agent (substance):
        text: Centrally acting hypotensive agent (substance)
        meaning: '372740001'
      Coumarin:
        text: Coumarin
        meaning: NCIT:C397
      Digitalis:
        text: Digitalis
        meaning: NCIT:C65385
      Diuretic:
        text: Diuretic
        meaning: NCIT:C448
      Dopamine Antagonist:
        text: Dopamine Antagonist
        meaning: NCIT:C66883
      Dipeptidyl-Peptidase IV Inhibitors:
        text: Dipeptidyl-Peptidase IV Inhibitors
        meaning: OMIT:0026067
      Enteral Nutrition:
        text: Enteral Nutrition
        meaning: OMIT:0005993
      Ezetimibe:
        text: Ezetimibe
        meaning: NCIT:C47529
      fibrate:
        text: fibrate
        meaning: TXPO:1000442
      Folate:
        text: Folate
        meaning: NCIT:C1444
      Dietary Supplement:
        text: Dietary Supplement
        meaning: NCIT:C1505
      Insulin Glargine:
        text: Insulin Glargine
        meaning: NCIT:C47564
      Thiazolidinedione Antidiabetic Agent:
        text: Thiazolidinedione Antidiabetic Agent
        meaning: NCIT:C98241
      glucagon-like peptide-1 receptor agonist:
        text: glucagon-like peptide-1 receptor agonist
        meaning: CHEBI:71196
      Heparin:
        text: Heparin
        meaning: NCIT:C539
      Insulin:
        text: Insulin
        meaning: NCIT:C2271
      Ipilimumab:
        text: Ipilimumab
        meaning: NCIT:C2654
      Iron:
        text: Iron
        meaning: NCIT:C598
      Isophane Insulin, Human:
        text: Isophane Insulin, Human
        meaning: OMIT:0001345
      Potassium-Sparing Diuretic:
        text: Potassium-Sparing Diuretic
        meaning: NCIT:C49186
      lactulose:
        text: lactulose
        meaning: CHEBI:6359
      Laxative:
        text: Laxative
        meaning: NCIT:C29697
      Metformin:
        text: Metformin
        meaning: NCIT:C61612
      Metformin Hydrochloride:
        text: Metformin Hydrochloride
        meaning: NCIT:C29251
      Methotrexate:
        text: Methotrexate
        meaning: NCIT:C642
      Pediatric Nutritional Supplement Drink:
        text: Pediatric Nutritional Supplement Drink
        meaning: NCIT:C74453
      Nitrate:
        text: Nitrate
        meaning: NCIT:C80487
      Nivolumab:
        text: Nivolumab
        meaning: NCIT:C68814
      None:
        text: None
        meaning: NCIT:C41132
      Insulin Aspart:
        text: Insulin Aspart
        meaning: NCIT:C47563
      Nonsteroidal Antiinflammatory Drug:
        text: Nonsteroidal Antiinflammatory Drug
        meaning: NCIT:C257
      Opioid:
        text: Opioid
        meaning: NCIT:C1506
      Anti-Arrhythmia Agents:
        text: Anti-Arrhythmia Agents
        meaning: OMIT:0002291
      Anti-PD1 Monoclonal Antibody:
        text: Anti-PD1 Monoclonal Antibody
        meaning: NCIT:C128037
      Pembrolizumab:
        text: Pembrolizumab
        meaning: NCIT:C106432
      Phenylpiperidine derivative (substance):
        text: Phenylpiperidine derivative (substance)
        meaning: '48070003'
      Proton Pump Inhibitor:
        text: Proton Pump Inhibitor
        meaning: NCIT:C29723
      Probiotics:
        text: Probiotics
        meaning: OMIT:0019903
      red yeast rice:
        text: red yeast rice
        meaning: DRON:00017677
      Reverse Transcriptase Inhibitor:
        text: Reverse Transcriptase Inhibitor
        meaning: NCIT:C1589
      sodium-glucose transport protein subtype 2 inhibitor:
        text: sodium-glucose transport protein subtype 2 inhibitor
        meaning: CHEBI:73273
      Sitagliptin:
        text: Sitagliptin
        meaning: NCIT:C73838
      statin:
        text: statin
        meaning: CHEBI:87631
      Steroid Compound:
        text: Steroid Compound
        meaning: NCIT:C843
      Sulfonylurea Antidiabetic Agent:
        text: Sulfonylurea Antidiabetic Agent
        meaning: NCIT:C97936
      Thiazide Diuretic:
        text: Thiazide Diuretic
        meaning: NCIT:C49185
      second generation antipsychotic:
        text: second generation antipsychotic
        meaning: CHEBI:65191
      Citrate-containing Alkalinizing Agent:
        text: Citrate-containing Alkalinizing Agent
        meaning: NCIT:C29369
      Xanthine Oxidase Inhibitor:
        text: Xanthine Oxidase Inhibitor
        meaning: NCIT:C1637
      Antibiotic:
        text: Antibiotic
        meaning: NCIT:C258
      Penicillin Antibiotic:
        text: Penicillin Antibiotic
        meaning: NCIT:C1500
        is_a: Antibiotic
      Aminoglycoside Antibiotic:
        text: Aminoglycoside Antibiotic
        meaning: NCIT:C2363
        is_a: Antibiotic
      Lincosamide Antibiotic:
        text: Lincosamide Antibiotic
        meaning: NCIT:C82922
        is_a: Antibiotic
      Cephalosporin Antibiotic:
        text: Cephalosporin Antibiotic
        meaning: NCIT:C357
        is_a: Antibiotic
      Trimethoprim:
        text: Trimethoprim
        meaning: NCIT:C908
        is_a: Antibiotic
      Antibacterial Agent:
        text: Antibacterial Agent
        meaning: NCIT:C52588
        is_a: Antibiotic
      Macrolide Antibiotic:
        text: Macrolide Antibiotic
        meaning: NCIT:C261
        is_a: Antibiotic
      Quinolone Antibiotic:
        text: Quinolone Antibiotic
        meaning: NCIT:C795
        is_a: Antibiotic
      Glycopeptide Antibiotic:
        text: Glycopeptide Antibiotic
        meaning: NCIT:C61101
        is_a: Antibiotic
      Carbapenems:
        text: Carbapenems
        meaning: OMIT:0016422
        is_a: Antibiotic
types:
  WhitespaceMinimizedString:
    name: WhitespaceMinimizedString
    typeof: string
    description: 'A string that has all whitespace trimmed off of beginning and end,
      and all internal whitespace segments reduced to single spaces. Whitespace includes
      #x9 (tab), #xA (linefeed), and #xD (carriage return).'
    base: str
    uri: xsd:token
  Provenance:
    name: Provenance
    typeof: string
    description: A field containing a DataHarmonizer versioning marker. It is issued
      by DataHarmonizer when validation is applied to a given row of data.
    base: str
    uri: xsd:token
